version: '3.5'
services:
    
    front: 
        build: front
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./library_front:/app
            - ./library_front/node_modules:/app/node_modules
        container_name: frontend_pomodorc
        build:
            context: ./library_front
        command: npm start
        ports:
            - "3000:3000"
