version: '3.5'
services:
    db:
        image: postgres
        container_name: library_db
        volumes:
            - ./data/db:/var/lib/postgresql
        env_file: ./library_back/.env
        ports:
            - 5432:5432
    server:

        depends_on:
            - db
        build: ./library_back
        container_name: library_back
        # restart: always
        working_dir: /server/library_back
        environment:
            - DJANGO_SETTINGS_MODULE=src.settings
        volumes:
            - .:/server/
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000

    front: 
        build: ./library_front
        container_name: library_front
        # restart: always
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./library_front:/app
            - ./library_front/node_modules:/app/node_modules
        command: npm start
        ports:
            - "3000:3000"
