name: CI_Build

on: [push]

# on: 
#   workflow_run: 
#     workflows: ["Test"]
#     branches: [main]
#     types:
#       - completed

jobs:
  build:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success'}}
    defaults:
      run:
        working-directory: ./


    steps:
    - uses: actions/checkout@v2


    - name: docker-compose up
      run: docker-compose up -d


    - name: docker-compose down
      run: docker-compose down
    

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    

    - name: DockerHub login
      env:
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      uses: docker/login-action@v1
      with:
        username: ${{env.USERNAME}}
        password: ${{env.PASSWORD}}


    - name: Build and push
      id: docker_build_server
      uses: docker/build-push-action@v2
      with:
        context: ./library_back
        file: ./library_back/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/trabalho-individual-2022-1-server:latest


    - name: Build and push Front
      id: docker_build_front
      uses: docker/build-push-action@v2
      with:
        context: ./library_front
        file: ./library_front/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/trabalho-individual-2022-1-front:latest